### ISSUE TITLE
Key Remapping

### ISSUE THREAD

**Issue by Byteron** [Merly23/GodotGamejam10#31]
I think this needs a bit of discussion
I recall maybe doing slow motion as reward for certain moves.

Otherwise, people indeed seem to prefer WASD
Also I've read people complaining about the trend and swear on playing with arrow keys (JohnGabrielUK said that^^)

So abilities should be accessible for both cases (cases being WASD and arrow keys)

And we got our game pad support anyways

BTW, if you want to try with game pad yourself right now only DPAD is working for movement
A is jump, B is attack, X is shooting, R1 is dashing and L1 is slow motion.

**Comment by ambivorous** [comment]
I agree with the complainers. WASD should only be used if your other hand needs to control the mouse, otherwise having your left hand be free to move over the entire alphabet is better for easier access to more keys.

But, if you just allow the players to pick their own keys then this problem goes away! :dancing_men:

**Comment by Byteron** [comment]
that is absolutely true.
I'll see if I can find how to remap keys
